//  coder.h     written by sebhall in April 2023
//
//  these functions generate CTC executable code 
//  from execution structures generated by the structuriser

#include <string>
#include <vector>
#include <map>